name: Workflow Dispatch 
on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - run: curl -i -H "Authorization:token {{ secrets.DISPATCH}}" https://api.github.com/repos/sirganya/local-ui/dispatches -d '{"event_type":"release"}'
       
        
