name: Workflow Dispatc
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - run: curl -X POST -u "${{secrets.sirganya}}:${{secrets.workflow_dispatch}}" -H "Accept:application/vnd.github.v3+json"  https://api.github.com/repos/sirganya/local-ui/dispatches -d '{"event_type":"release"}' 
